ouicheur:
  app_origin: ""
  trust_proxy: false
run_as:
  user: 1000
  group: 1000
network:
  web_port:
    bind_mode: published
    port_number: 31000
    host_ips: []
resources:
  limits:
    cpus: 2
    memory: 2048
ix_volumes:
  data: /opt/tests/mnt/data
  backups: /opt/tests/mnt/backups
storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  backups:
    type: ix_volume
    ix_volume_config:
      dataset_name: backups
      create_host_path: true
