images:
  image:
    repository: ghcr.io/hloiseau/ouicheur
    tag: sha-35e849507983f3e5139b7b4f34f13899214a8f46
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
consts:
  app_container_name: ouicheur
  perms_container_name: permissions
